### ISSUE TITLE
Foreign key constrains and multiple table options

### ISSUE THREAD

**Issue by PumpkinSeed** [PumpkinSeed/sqlfuzz#19]
Feature request from reddit:

_Does it support and understand constraints when given multiple tables?
And does it handle FK? Eg; If my T2 has a FK to T1 and i fuzz them in the correct order will the tool figure it out?_

So make the tool understand constrains even if the one table passed and add the feature to handle more tables with comma separated.

**Comment by breml** [comment]
This article ([POSTGRESQL: FOREIGN KEYS AND INSERTION ORDER IN SQL](https://www.cybertec-postgresql.com/en/postgresql-foreign-keys-and-insertion-order-in-sql/)) may help, it contains a recursive PostgreSQL query, which returns tables in the correct inserting order if they depend on each other by foreign keys.

**Comment by srinidhis94** [comment]
I can take this up :+1:
